"use client";

import React, { useState } from 'react';
import { X } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose }) => {
  const [activeTab, setActiveTab] = useState<'terms' | 'privacy'>('terms');

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 backdrop-blur-sm">
      <div className="relative w-full max-w-4xl max-h-[90vh] bg-[#1A2537] rounded-2xl shadow-2xl border border-gray-700/50 flex flex-col mx-4">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-700/50">
          <div className="flex gap-4">
            <button
              onClick={() => setActiveTab('terms')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeTab === 'terms'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-800/50 text-gray-400 hover:text-white'
              }`}
            >
              Terms of Service
            </button>
            <button
              onClick={() => setActiveTab('privacy')}
              className={`px-4 py-2 rounded-lg font-semibold transition-all ${
                activeTab === 'privacy'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-800/50 text-gray-400 hover:text-white'
              }`}
            >
              Privacy Policy
            </button>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-gray-700/50 transition-colors"
          >
            <X className="w-6 h-6 text-gray-400" />
          </button>
        </div>

        {/* Content */}
        <div className="overflow-y-auto p-6 space-y-8 text-gray-300">
          {activeTab === 'terms' ? (
            <div className="space-y-8">
              <header className="space-y-2">
                <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
                <p className="text-sm text-gray-400">Effective date: 2025-08-20</p>
              </header>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Acceptance of Terms</h2>
                <p>By accessing or using ReFocused, you agree to these Terms. If you do not agree, do not use the service.</p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Use of the Service</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You must be at least 13 years old (or the age of digital consent in your jurisdiction).</li>
                  <li>You are responsible for your account security and all activity under it.</li>
                  <li>You will not attempt to bypass security, rate limits, or abuse any endpoints; automated scraping, spamming, and DDoS are prohibited.</li>
                  <li>You retain ownership of your content. You grant us a limited license to process your content solely to operate and improve the service.</li>
                </ul>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Acceptable Use</h2>
                <p>Prohibited content includes illegal, infringing, harmful, or abusive material. Prohibited conduct includes reverse engineering, unauthorized access, and interfering with service operations.</p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">AI and Third-Party Services</h2>
                <p>Certain features proxy to upstream services (e.g., AI chat, email, feature voting). You agree to comply with their acceptable use policies and understand that responses may be generated by third-party models.</p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Fees</h2>
                <p>If paid plans are introduced, separate terms will apply. You will be notified in advance.</p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Termination</h2>
                <p>We may suspend or terminate access for policy or legal violations, or to protect the service. You may close your account at any time.</p>
              </section>

              <section className="grid gap-6 md:grid-cols-2">
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">Disclaimers</h3>
                  <p>The service is provided "as is" and "as available" without warranties of any kind.</p>
                </div>
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">Limitation of Liability</h3>
                  <p>To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages.</p>
                </div>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Changes to These Terms</h2>
                <p>We may modify these Terms; material changes will be communicated, and continued use constitutes acceptance.</p>
              </section>
            </div>
          ) : (
            <div className="space-y-8">
              <header className="space-y-2">
                <h1 className="text-3xl font-bold text-white">Privacy Policy</h1>
                <p className="text-sm text-gray-400">Effective date: 2025-08-20</p>
              </header>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-4">
                <h2 className="text-xl font-semibold text-white">Overview</h2>
                <p>
                  This Privacy Policy explains how ReFocused ("we", "us", "our") collects, uses, shares, and
                  protects your information when you use the ReFocused application and APIs.
                </p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-4">
                <h2 className="text-xl font-semibold text-white">Information We Collect</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>
                    <span className="font-medium text-gray-200">Account data</span>: email, name, profile picture, OAuth identifiers (Google),
                    timestamps (created_at, last_login).
                  </li>
                  <li>
                    <span className="font-medium text-gray-200">App data you provide</span>: goals, habits, mood entries (happiness/focus/stress),
                    journal collections/entries (which may contain sensitive information), calendars, study sets,
                    trackings, voting choices, feedback, and email subscription status.
                  </li>
                  <li>
                    <span className="font-medium text-gray-200">Technical data</span>: IP address (for security and rate limiting), user agent, device
                    metadata, request metadata, security logs, monitoring metrics.
                  </li>
                  <li>
                    <span className="font-medium text-gray-200">Authentication/session data</span>: hashed passwords (bcrypt), access/refresh tokens
                    (cookies), session flags.
                  </li>
                  <li>
                    <span className="font-medium text-gray-200">AI/chat content</span> you submit when using AI features (proxied via our backend to
                    upstream services).
                  </li>
                </ul>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-4">
                <h2 className="text-xl font-semibold text-white">How We Use Information</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide, operate, and improve the service (feature delivery, personalization, performance).</li>
                  <li>Security and abuse prevention (rate limiting, anomaly detection, fraud prevention, authentication).</li>
                  <li>Customer support and service communications.</li>
                  <li>Optional marketing emails (only with your consent).</li>
                  <li>Research, analytics, and product development using aggregated/anonymized data.</li>
                </ul>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Legal Bases (EEA/UK)</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Contract: to provide the service you request.</li>
                  <li>Legitimate interests: security, fraud prevention, service improvement.</li>
                  <li>Consent: marketing emails, certain cookies, and where required for AI or analytics.</li>
                  <li>Legal obligations: compliance with applicable laws.</li>
                </ul>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Sharing and Disclosures</h2>
                <p>We do not sell your personal information. We share data with service providers under contract, strictly for service delivery, including:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Cloud hosting and infrastructure (e.g., AWS: API Gateway/Lambda, database, storage; Redis cache).</li>
                  <li>Email delivery and transactional communications.</li>
                  <li>Error monitoring and observability (e.g., optional Sentry/OpenTelemetry).</li>
                </ul>
                <p>We may disclose information to comply with law, protect rights and safety, or in connection with a merger/acquisition.</p>
              </section>

              <section className="grid gap-6 md:grid-cols-2">
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">International Transfers</h3>
                  <p>Where data is transferred internationally, we use safeguards such as Standard Contractual Clauses and provider commitments.</p>
                </div>
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">Data Retention</h3>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>Account and in-app content: retained until you delete it or close your account.</li>
                    <li>Security logs and audit events: typically up to 12 months unless required otherwise.</li>
                    <li>Rate-limit counters and ephemeral cache: short TTLs (often reset at midnight UTC).</li>
                    <li>Deleted emails: stored up to 72 hours to enforce account recreation safeguards.</li>
                  </ul>
                </div>
              </section>

              <section className="grid gap-6 md:grid-cols-2">
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">Your Rights</h3>
                  <p>
                    Depending on your location, you may have rights to access, correct, delete, port, restrict, or object to processing of your
                    personal data, and to withdraw consent. Contact us to exercise these rights.
                  </p>
                </div>
                <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                  <h3 className="text-lg font-semibold text-white">Children's Privacy</h3>
                  <p>The service is not intended for children under 13 (or older age as required by local law). We do not knowingly collect such data.</p>
                </div>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
                <h2 className="text-xl font-semibold text-white">Security</h2>
                <p>
                  We employ industry-standard security measures including HTTPS/TLS, bcrypt password hashing, token-based auth, HTTP-only cookies,
                  rate limiting, input validation, and defense-in-depth monitoring. No system is 100% secure; please use strong, unique passwords and
                  keep credentials safe.
                </p>
              </section>

              <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6">
                <h2 className="text-xl font-semibold text-white mb-2">Contact</h2>
                <p>For privacy inquiries or rights requests, contact: <span className="text-blue-400">support@refocused.app</span></p>
              </section>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
