export default function TermsOfServicePage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8 text-gray-300">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
        <p className="text-sm text-gray-400">Effective date: 2025-08-20</p>
      </header>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Acceptance of Terms</h2>
        <p>By accessing or using ReFocused, you agree to these Terms. If you do not agree, do not use the service.</p>
      </section>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Use of the Service</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You must be at least 13 years old (or the age of digital consent in your jurisdiction).</li>
          <li>You are responsible for your account security and all activity under it.</li>
          <li>You will not attempt to bypass security, rate limits, or abuse any endpoints; automated scraping, spamming, and DDoS are prohibited.</li>
          <li>You retain ownership of your content. You grant us a limited license to process your content solely to operate and improve the service.</li>
        </ul>
      </section>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Acceptable Use</h2>
        <p>Prohibited content includes illegal, infringing, harmful, or abusive material. Prohibited conduct includes reverse engineering, unauthorized access, and interfering with service operations.</p>
      </section>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">AI and Third-Party Services</h2>
        <p>Certain features proxy to upstream services (e.g., AI chat, email, feature voting). You agree to comply with their acceptable use policies and understand that responses may be generated by third-party models.</p>
      </section>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Fees</h2>
        <p>If paid plans are introduced, separate terms will apply. You will be notified in advance.</p>
      </section>

      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Termination</h2>
        <p>We may suspend or terminate access for policy or legal violations, or to protect the service. You may close your account at any time.</p>
      </section>

      <section className="grid gap-6 md:grid-cols-2">
        <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
          <h3 className="text-lg font-semibold text-white">Disclaimers</h3>
          <p>The service is provided “as is” and “as available” without warranties of any kind.</p>
        </div>
        <div className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
          <h3 className="text-lg font-semibold text-white">Limitation of Liability</h3>
          <p>To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages.</p>
        </div>
      </section>



      <section className="rounded-xl border border-gray-700/50 bg-gray-800/40 p-6 space-y-3">
        <h2 className="text-xl font-semibold text-white">Changes to These Terms</h2>
        <p>We may modify these Terms; material changes will be communicated, and continued use constitutes acceptance.</p>
      </section>
    </div>
  );
}



